version: "3.8"

services:
  exercise-3.1:
    image: prabhat42/devopswithdocker-pokedex
    container_name: exercise-3.2
    ports:
      - 5000:5000
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
