name: Re-Deploy Docker Image to Render

on:
  workflow_run:
    workflows:
      - Deploy to Dockerhub
    types:
      - completed
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy to Render
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$DEPLOY_HOOK"
