name: Deploy Docker Image to Render

on:
  workflow_run:
    workflows:
      - Deploy to Dockerhub
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: my-dockerhub-user/my-app:my-tag
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
